# docker-compose.yml
version: "3"
services:
  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "5000:5000"
    command:
      node index.js
    volumes:
      - ./client:/app/
      - /app/node_modules

  server:
    build: ./server
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:test123@postgres:5432/directory
      NODE_ENV: development
      PORT: 8000
    ports:
      - "8000:8000"
    command: 
      yarn run dev
    volumes:
      - ./server:/app/
      - /app/node_modules

  postgres:
    image: postgres:14-alpine
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: directory
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
